# Generated by Django 4.0.3 on 2022-04-09 09:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_alter_image_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='favorite',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='gallery.image', verbose_name='Favorite')),
            ],
            options={
                'unique_together': {('author', 'image')},
            },
        ),
    ]
