# Generated by Django 4.0.3 on 2022-04-09 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_image_favorite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='favorite',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
